### ISSUE TITLE
CONFIG:  Trakt defaults added to config every startup

### ISSUE THREAD

**Issue by amoghg** [elmerfdz/docker-traktarr#18]
After modifying the config to remove trakt defaults for automatic mode and restarting the container, the unwanted config options are added back. 

Added 'interval' to config option 'movies': 20
Added 'trending' to config option 'movies': 3
Added 'popular' to config option 'movies': 3
Added 'boxoffice' to config option 'movies': 10
Added 'interval' to config option 'shows': 48
Added 'trending' to config option 'shows': 1
Added 'popular' to config option 'shows': 1
New config options were added, adjust and restart!

Any way to fix this except for modifying config.py and manually removing them?

**Comment by elmerfdz** [comment]
Could you please post your docker-compose or docker run command for Traktarr? Have you mounted /config correctly?

**Comment by amoghg** [comment]
I'm running it on unraid. 

This is the docker run command: 
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Traktarr' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'DELAY'='2.5' -e 'SORT'='rating' -e 'NOSEARCH'='no' -e 'NOTIFICATIONS'='yes' -e 'BLACKLIST'='yes' -e 'RUNNOW'='yes' -e 'SKIPUPDATE'='yes' -e 'APP_BRANCH'='master' -e 'PUID'='99' -e 'PGID'='100' -v '/mnt/user/appdata/Traktarr':'/config':'rw' 'eafxx/traktarr:latest' `

I've tried modifying the config.json from /mnt/user/appdata/Traktarr/config.json as well as from the docker exec, and setting it to 
`
{
  "automatic": {
    "movies": {
      "interval": 20,
      "lists": {
        "https://trakt.tv/users/user/lists/my_movies": 10
      }
    },
    "shows": {
      "interval": 48,
      "lists": {
        "https://trakt.tv/users/user/lists/my_shows": 10
      }
    }
  },...
`
but as soon as the docker is restarted, it gets overwritten with 

`Added 'interval' to config option 'movies': 20
Added 'trending' to config option 'movies': 3
Added 'popular' to config option 'movies': 3
Added 'boxoffice' to config option 'movies': 10
Added 'interval' to config option 'shows': 48
Added 'trending' to config option 'shows': 1
Added 'popular' to config option 'shows': 1
New config options were added, adjust and restart!
`

The only way I could get it to not "add" these options was to update the l3uddz/traktarr:misc/config/config.py base_config and editing out these options. 

To think of it, it might be an issue against the upstream traktarr and not the docker.

**Comment by bmahlbrand** [comment]
I'm experiencing the same issue w/docker, here's my yml - it clobbers the local config.json I have at `~/docker-services/traktarr/config/config.json`. Is there a workaround?

```
  traktarr:
      container_name: traktarr
      image: eafxx/traktarr
      volumes:
          - ~/docker-services/traktarr/config:/config
      environment:
      - TRAKTARR_CONFIG=/config/config.json
      - TRAKTARR_CACHEFILE=/config/cache.db
      - TRAKTARR_LOGFILE=/config/traktarr.log
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DELAY=2.5
      - SORT=rating
      - NOSEARCH=yes
      - NOTIFICATIONS=yes
      - BLACKLIST=yes
      - RUNNOW=no
      - SKIPUPDATE=no
      - APP_BRANCH=master
```
